main: com.benjnet.hungergames.Main
name: HungerGames
version: "1.0"
depend: [Multiverse-Core, Multiverse-NetherPortals]
api-version: "1.15"
author: zweetdreams

commands:
  hg:
    description: /hg help
  a:
    description: accept team invite
    usage: lobby
  d:
    description: decline team invite
    usage: lobby
  scoreboard:
    description: toggle scoreboard
    usage: misc
  ready:
    description: ready up for HG
    usage: lobby
